<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [43]:
x = -1
assert x >= 0, "x is becoming negative!"

print(x)

AssertionError: x is becoming negative!

### 1.2 try-except

In [2]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")


Give me a number and I will calculate its square.hello
Oh oh! I cannot square hello!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [7]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121

121

### 2.2 Docstrings

In [11]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [17]:
def my_function(angle, trig_function):
        return trig_function(angle)

my_function(np.pi/2, np.sin) 

my_function(np.pi/2, np.cos)

my_function(np.pi/2, lambda x: np.cos(2*x))


-1.0

### 2.4 More unpacking

In [18]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [19]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [20]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [21]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [28]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])


def add(x, y):
    return x+y

print (add(x, y))

[100 100 100 100 100]


In [29]:
def subtract(x, y):
    return x-y

print (subtract(x, y))

[-28 -32 -12  52 -46]


In [45]:
def multiply(x, y):
    return x*y

print (multiply(x, y))

[-64 -66 -56 -24 -73]


In [59]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def divide(x, y):
    assert np.all(y != 0), "cannot divide by 0"
    return x/y
    
#np.any returns as long as one is true
#np.all checks for all values

print (divide(x, y))

[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 2 :  A better calculator II

In [60]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])


def add(x, y):
    return x+y

print (add(x, y))

[100 100 100 100 100]


In [61]:
def subtract(x, y):
    return x-y

print (subtract(x, y))

[-28 -32 -12  52 -46]


In [62]:
def multiply(x, y):
    return x*y

print (multiply(x, y))

[2304 2244 2464 1824 1971]


In [4]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def divide(x, y):
    np.seterr(all='raise')
    try:
        return x/y
    except:
        print(f" Cannot divide when y is {y}!")
        
print (divide(x, y))            

 Cannot divide when y is [64 66 56 24  0]!
None
