<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [11]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting("Super Man")

greeting("Batman")

'Hello Batman! So, nice to meet you!'

In [30]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

basic_stats([1, 2, 3, 4, 5])

(1, 5, 3.0)

### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [3]:
my_short_function = lambda name: f"Hello {name}!"

my_short_function(name="Batman")

'Hello Batman!'

In [7]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element in ascending order)
    
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element
    
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [9]:
def greeting(name='Batman'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting()

'Hello Batman! So, nice to meet you!'

In [12]:
print('I', 'am', 'Batman!')                 # Just for comparison

print('I', 'am', 'Batman!', sep='---')  


I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

The else statement is an optional argument, hence the code can still work without it

## Exercise 2 :  Calculator functions

In [51]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def add(x, y):
    return x + y

print(add(x, y))

[100 100 100 100 100]


In [52]:
def subtract(x, y):
    return x - y

print (subtract(x, y))

[-28 -32 -12  52 -46]


In [53]:
def multiply(x, y):
    return x*y

print (multiply(x, y))

[2304 2244 2464 1824 1971]


In [45]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def divide(x,y):
    for integers in y:
        if integers == 0: 
            return "error"
    return x/y
        
print(divide(x,y))
    


[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [38]:
def max_info(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.max(), np_numbers.argmax()

max_info([40, 27, 83, 44, 74, 51, 76, 77, 10, 49])

(83, 2)