<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [19]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

### 1.2 Accessing data from a list (or array)

In [20]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])
print(py_super_names[2])

print(py_super_names[-1])   # Reverse indexing
print(py_real_names[-3])

Natasha Romanoff
Doctor Strange
Doctor Strange
Natasha Romanoff


### 1.3 Accessing data from a dictionary

In [25]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(superhero_info["Natasha Romanoff"])
print(superhero_info["Tony Stark"])

superhero_info.keys()


superhero_info.values()

Black Widow
Iron Man


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [ ]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]


## 2 Lists vs. Arrays

### 2.1 Size

In [31]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
        
len(py_list_2d)

len(np_array_2d)

np_array_2d.shape


(10, 2)

### 2.2 Arrays are fussy about type

In [32]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [35]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
        
np_array + 10 # - array
#py_list + 10 wont work - list

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [38]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2 # - lists

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [39]:
np_array_1 + np_array_2 # - arrays

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list*2
# list copy twice


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [41]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2

# py_list**2 wont work in this case 

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3     # Works, but what IS the question?

# py_list > 3  -- Won't work!

np_array == 3  

np_array > 3  


array([False, False, False,  True,  True])

### 2.8 Mathematics

In [55]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list)     # sum() is a base Python function

max(py_list)     # max() is a base Python function

min(py_list)     # min() is a base Python function

#py_list.sum() - Won't work!

np_array.sum()

np_array.mean()

np_array.max()

np_array.min()

1

## Exercise 1 :  Total recall?

lists are stored as py_ while arrays are stored as np_

numpy needs be imported for arrays but not for lists

dictionary stores data and allows easy retrieval of specific data stored in it

## Exercise 2 :  Index me

In [5]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'


a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [18]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"}

superhero = {k.lower():v.upper() for k,v in superhero_info.items()}
    
print (superhero)

{'natasha romanoff': 'BLACK WIDOW', 'tony stark': 'IRON MAN', 'stephen strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [31]:
py_list = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
np_array = np.array(py_list)

np_array == 1

sum(np_array == 1)

9